spring:
  datasource:
    url: jdbc:postgresql://localhost/pessoa1?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
